apiVersion: v1
kind: Service
metadata:
  name: cafeweb1
  labels:
    app: cafeapp
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cafeapp
    tier: frontend
  type: NodePort 

